version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: inventory_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_command_center
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: inventory_app
    depends_on:
      - postgres
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      DB_NAME: inventory_command_center
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: 5432

volumes:
  postgres_data:
